# Travis CI should run a command like:
# xctool -project SSVC.xcodeproj -scheme SSVCTests -sdk iphonesimulator7.0 build test

language: objective-c
xcode_project: SSVC.xcodeproj 
xcode_scheme: SSVCTests
xcode_sdk: iphonesimulator7.0
