# Travis CI should run a command like:
# xctool -project SSVC.xcodeproj -scheme SSVCTests -sdk iphonesimulator7.0 build test

language: objective-c
before_script:
  - brew update
  - brew upgrade xctool
xcode_project: SSVC.xcodeproj 
xcode_scheme: SSVCTests
xcode_sdk: iphonesimulator7.0
